stages:
  - test

test:
  stage: test
  image: python:3.7
  script:
    - pip install -U pip setuptools
    - pip install pip-tools
    - pip-sync requirements.txt requirements-dev.txt
    - ./manage.py test
