# Generated by Django 3.0.4 on 2020-04-08 00:15

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations
import hyakumori_crm.crm.models.forest


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forest',
            name='contracts',
            field=django.contrib.postgres.fields.jsonb.JSONField(db_index=True, default=hyakumori_crm.crm.models.forest.DefaultForest.contracts, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
