# Generated by Django 3.0.4 on 2020-04-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_customer_contact_rels_20200421_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='archive',
            name='future_response',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='archive',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='archive',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='archivecustomer',
            name='is_our_participant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='archivecustomer',
            name='is_their_participant',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='archive',
            name='archive_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='object_id',
            field=models.CharField(max_length=255),
        ),
    ]
