name: Lint

on:
  push:
    branches: [ next ]
  pull_request:
    branches: [ next ]

  workflow_dispatch:

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Lint Vue
        run: |
          yarn install
          yarn lint --no-fix
