name: Lint

on:
  push:
    branches: ['**']

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      MAPCONFIG: ${{secrets.MAPCONFIG}}
    steps:
      - uses: actions/checkout@v2

      - name: create mapconfig
        run: jq -rc -n env.MAPCONFIG > mapconfig.json

      - name: Lint Vue
        run: |
          yarn install
          yarn lint --no-fix
