name: Lint

on:
  push:
    branches: ['**']

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: schdck/create-env-json@v2
        id: create-mapconfig
        with:
          file-name: 'mapconfig.json'
          tilesources: ${{ secrets.TILESOURCES }}
          cadastral: ${{ secrets.CADASTRAL }}
          center: ${{ secrets.CENTER }}
          zoom: ${{ secrets.ZOOM }}

      - name: Lint Vue
        run: |
          yarn install
          yarn lint --no-fix
