name: Deploy Staging to S3

on:
  pull_request:
    branches: [ next ]
  push:
    branches: [ use-staging ]

jobs:
  staging:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      BACKEND_URL: ${{ secrets.BACKEND_URL }}
      VUE_APP_GRAPHQL_HTTP: ${{ secrets.VUE_APP_GRAPHQL_HTTP }}
      VUE_APP_REST_HTTP: ${{ secrets.VUE_APP_REST_HTTP }}
    steps:
      - uses: actions/checkout@v2

      - uses: schdck/create-env-json@v1
        id: create-mapconfig
        with:
          file-name: 'mapconfig.json'
          TILESOURCES: ${{ secrets.MAPCONFIG_TILESOURCES }}
          CADASTRAL: ${{ secrets.MAPCONFIG_CADASTRAL }}
          CENTER: ${{ secrets.MAPCONFIG_CENTER }}
          ZOOM: ${{ secrets.MAPCONFIG_ZOOM }}

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Stage
        uses: reggionick/s3-deploy@v3
        with:
          folder: dist
          bucket: ${{ secrets.S3_BUCKET_STAGING }}
          bucket-region: ${{ secrets.AWS_DEFAULT_REGION_STAGING }}
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_STAGING }}
          invalidation: /
          delete-removed: true
          no-cache: true
          private: true
