name: Lint and Test

on:
  push:
    branches: [ next ]
  pull_request:
    branches: [ next ]

  workflow_dispatch:

jobs:
  frontend:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        
      - name: Lint Vue
        run: |
          cd hyakumori_crm/static/hyakumori_crm
          yarn install
          yarn lint --no-fix
     
  backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    services:
      postgres:
        image: postgres:11-alpine
        env:
          POSTGRES_DB: hyakumori
          POSTGRES_USER: runner
          POSTGRES_PASSWORD: "youC4nP4ass"
          POSTGRES_HOST_AUTH_METHOD: trust


    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      env: 
        HYAKUMORI_LIGHT_BUILD: 1
      run: |
        python -m pip install --upgrade pip
        pip install -U pip setuptools
        pip install '.[dev]'

    - name: Test with pytest
      env:
        DATABASE_URL: postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DB
      run: |
        pytest tests
